version: '3.8'

services:
  # خدمة الـ Web (PHP + Apache)
  php-server:
    build: .
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # خدمة قاعدة البيانات (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ecommerce_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"

  # أداة phpMyAdmin (الـ GUI المطلوب)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80" # سنفتح الواجهة الرسومية على المنفذ 8081
    environment:
      PMA_HOST: db # يخبر phpMyAdmin بالاتصال بحاوية قاعدة البيانات
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db